name: fittrack_pro
description: "Fitness tracking app with advanced UI and native integrations."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  go_router: ^16.0.0
  video_player: ^2.10.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/videos/
    - assets/images/
    - assets/fonts/
    - assets/svgs/
    - assets/gifs/

  fonts:
    - family: archivo
      fonts:
        - asset: assets/fonts/archivo/Archivo-Thin.ttf
          weight: 100
        - asset: assets/fonts/archivo/Archivo-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/archivo/Archivo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/archivo/Archivo-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/archivo/Archivo-Light.ttf
          weight: 300
        - asset: assets/fonts/archivo/Archivo-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/archivo/Archivo-Regular.ttf
          weight: 400
        - asset: assets/fonts/archivo/Archivo-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/archivo/Archivo-Medium.ttf
          weight: 500
        - asset: assets/fonts/archivo/Archivo-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/archivo/Archivo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/archivo/Archivo-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/archivo/Archivo-Bold.ttf
          weight: 700
        - asset: assets/fonts/archivo/Archivo-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/archivo/Archivo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/archivo/Archivo-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/archivo/Archivo-Black.ttf
          weight: 900
        - asset: assets/fonts/archivo/Archivo-BlackItalic.ttf
          style: italic
          weight: 900
